
jenkins_dir:
  {
    path: "/home/ubuntu/jenkins-files/",
    type: "directory",
  }


templates:
  - {
      src: "master-volume.j2",
      dest: "/home/ubuntu/jenkins-files/master-volume.yaml"
    }
  

cluster_nodes: ""